version: 2.1
orbs: 
  terraform: circleci/terraform@3.0.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      # - run:
      #     command: >-
      #       echo "credentials \"app.terraform.io\" {token =
      #       \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      #     name: Create .terraformrc file locally
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 0.14.2
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .
      - terraform/init:
          backend: true
          backend_config_file: testingtf.tfstate
          path: .
      - terraform/plan:
          backend_config_file: testingtf.tfstate
          path: .
      - terraform/apply:
          backend_config_file: testingtf.tfstate
          path: .
      - terraform/destroy:
          path: .
    working_directory: ~/Terraform
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle