version: 2.1

jobs:

  init-plan:
    docker: 
      - image: hashicorp/terraform:light
    # working_directory: /terraform-sandbox/
    steps:
      - checkout
      - run:
          name: terraform init plan fmt
          command: |
            terraform init
            pwd
            terraform fmt .
            terraform plan
  apply:
    docker: 
      - image: hashicorp/terraform:light
    # working_directory: /terraform-sandbox/
    steps:
      - checkout
      - run:
           name: terraform apply
           command: |
            terraform apply -auto-approve
  destroy:
    docker: 
      - image: hashicorp/terraform:light
    # working_directory: /terraform-sandbox/
    steps:
      - checkout
      - run:
           name: terraform destroy
           command: |
            terraform destroy -auto-approve
            

workflows:
    deploy:
      jobs:
        - init-plan
        - hold:
            type: approval
            requires:
              - init-plan
        - apply:
            requires:
              - hold
        - destroy:
            requires:
              - apply

      

