version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@3.1.1
executors:
  docker-executor:
    docker:
      - image: cimg/python:3.9.6
jobs:
  aws-cli-install:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          command: |
           aws --version
  init-plan:
    working_directory: ~/project/terraform
    executor: docker-executor 
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
      - attach_workspace:
          at: .
      - run:
          name: terraform init plan fmt
          command: |
            cd terraform
            terraform init -input=false
            terraform fmt .
            terraform plan -input=false
  apply:
    working_directory: /terraform
    docker: 
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light 
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
           name: terraform apply
           command: |
            terraform apply -auto-approve
  destroy:
    working_directory: /terraform
    docker: 
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
           name: terraform destroy
           command: |
            terraform destroy -auto-approve

workflows:
    deploy:
      jobs:
        - init-plan
        - hold:
            type: approval
            requires:
              - init-plan
        - apply:
            requires:
              - hold
        - destroy:
            requires:
              - hold

      
