version: 2.1

jobs:
  init-plan:
    working_directory: /terraform-sandbox/terraform
    docker: 
      - image: hashicorp/terraform:light   
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform init plan fmt
          command: |
            terraform init
            terraform fmt .
            terraform plan
  apply:
    working_directory: /terraform-sandbox/terraform
    docker: 
      - image: hashicorp/terraform:light 
    steps:
      - attach_workspace:
          at: .
      - run:
           name: terraform apply
           command: |
            terraform apply -auto-approve
  destroy:
    working_directory: /terraform-sandbox/terraform
    docker: 
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
           name: terraform destroy
           command: |
            terraform destroy -auto-approve

workflows:
    deploy:
      jobs:
        - init-plan
        - hold:
            type: approval
            requires:
              - init-plan
        - apply:
            requires:
              - hold
        - destroy:
            requires:
              - hold

      

