version: 2.1

jobs:
  init-plan:
    working_directory: /terraform-sandbox/terraform
    docker: 
      - image: hashicorp/terraform:light   
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform init plan fmt
          command: |
            terraform init
            pwd
            terraform fmt .
            terraform plan
  apply:
    working_directory: /terraform-sandbox/terraform
    docker: 
      - image: hashicorp/terraform:light 
    steps:
      - attach_workspace:
          at: .
      - run:
           name: terraform apply
           command: |
            terraform apply -auto-approve
  destroy:
    working_directory: /terraform-sandbox/terraform
    docker: 
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
           name: terraform destroy
           command: |
            terraform destroy -auto-approve

set_terraform_environment: &set_terraform_environment
  run:
    name: set terraform environment
    command: |
      cd && touch $BASH_ENV
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        echo 'export TERRAFORM_ENVIRONMENT=production' >> $BASH_ENV
      else
        echo 'export TERRAFORM_ENVIRONMENT=staging' >> $BASH_ENV
      fi

workflows:
    deploy:
      jobs:
        - set_terraform_environment
        - init-plan
        - hold:
            type: approval
            requires:
              - init-plan
        - apply:
            requires:
              - hold
        - destroy:
            requires:
              - hold

      

